---
title: "Introduction to the Analysis of Binary and Time-to-Event Data"
output:
  slidy_presentation:
    fig_width: 9
    fig_height: 5
    font_adjustment: 3
    transition: faster
    css: slidystyles.css
    footer: metrumrg &copy 2021

---


<!-- # Why Start Here? -->

<!-- * The beginning is a very good place to start. -->
<!-- * Why start with GLMs? -->
<!-- * Why start with binary endpoints? -->
<!-- * Why time-to-event analysis? -->

# Course objectives

We want you to finish this course with: 

* Conceptual understanding & basic intuitions for the analysis of exposure-response with binary and time-to-event (TTE) endpoints.
* Enough hand-on experience to enable further self-exploration.

_After_ the course self-exploration of those materials will also give you: 

* Specific tips, tricks, and recipes for getting the job done "soup to nuts" in R and Stan


---- 

# What this course isn't

* __Not__ primarily a course on R programming.
    * We expect a full range of experience levels. 
    * R techniques __not__ taught systematically "from the ground up"
    * Instead: __"copy and modify" / "learn by playing"__

* __Not__ a comprehensive course on the analysis of odd-type data
    * We emphasize the aspects that we have found most essential in pharmacometric research, specifically in exposure-response.
    


----

# Course organization

* 3 4 hour sessions
    * Thursday Nov 3 PM 1:00-5:00
    * Friday Nov 4 AM 8:00-12:00
    * Friday Nov 4 PM 1:00-5:00
* Each session is a mix of 
    * Didactic (html slides that you can compile from Rmd if you want) 
    * Hands-on learning (Rmd workbooks that probably won't compile until you edit them)
    * Solutions not included, but we will send by email approximately 1 week from now
* Course materials are organized according to a 4 1/2 day format; given time constraints we will mix and match a bit.     



----

# Session 1

Only material in **bold** will be covered. Material in _italics_ is yours to keep for self-exploration

Slides: 

* **Day1/Overview.html** 
* _Day1/Confounded-Exposure-Response.html_
* **Day1/LogisticRegression.html (partial)**
* **Day1/LogisticRegression_bayes.html**

Workbooks: 

* **Day1/Workbook01.Rmd** ; binomial basics in R
* _Day1/Workbook02.Rmd_ (partial) ; EDA prior to modeling 
* _Day1/Workbook3.Rmd_ ; measures of effect for binomial outcomes
* **Day1/Workbook04.Rmd** ; glm syntax in R
* _Day1/Workbook05.html_ ; residuals and VPCs
* **Day1/Workbook_Bayes01.Rmd** ; logistic regression with brms
    
----

# Session 2

Slides

* **TTE_Introduction.html** (partial; we will skip slides 29-53 on Cox PH) 
* **Day3/BayesianTTE_brms.html** 
 
Workbooks

* **Day2/Workbook01.Rmd**; relationships between hazard, survival, etc. 
* **Day2/Workbook02.Rmd**; Kaplan Meier estimates
* _Day2/Workbook03.Rmd_; summary measures of surv curves
* _Day2/Workbook04.Rmd_; Cox PH
* **Day2/Workbook05.Rmd**; flexsurvreg, VPCs
* **Day3/Workbook01.Rmd**; TTE with brms

----

# Session 3

Slides 

* **Day3/Stan_Intro.html** (partial, up to slide 23)
* **Day4/Time_varying_hazard.html** (as time allows)
 
Workbooks

* **Day3/Workbook_Stan01.Rmd** ; logistic regression w / rstan
* **Day3/weibull_example.Rmd** ; Weibull TTE w/ rstan
* **Day4/Workbook_time_varying.Rmd** ; Time-varying hazards w/ rstan



# Notes on breakout sessions

* Please hail a teaching assistant at any time if you are stuck. 
* We will usually take 15-20 minutes for each breakout; use this for bio breaks as well.
* No need to complete everything here. Get hands dirty. Try to get to a point that will enable further self-exploration. 


<!-- ---- -->

<!-- # Why start with GLMs?  -->

<!-- They are broadly useful. -->

<!-- * <red>Binary</red> (one focus of this course) -->
<!-- * Ordered categorical (e.g. grade of adverse event) -->
<!-- * Continuous -->
<!--     * bounded below (e.g. Lognormal residuals),  -->
<!--     * bounded above and below (e.g. Beta residuals),  -->
<!--     * unbounded (e.g. Normal residuals)  -->
<!-- * Counts -->
<!-- * <red>Time-to-event</red> (Many TTE models are GLMs, even though they are generally fit using slightly different machinery) -->


<!-- ---- -->

<!-- # Why start with GLMs? Mind-expanding. -->

<!-- * If you are coming from a Pop PK background, moving away from models with Normal (or log-Normal) residuals may force you to think at a new level of abstraction.  -->
<!-- * If you are not used to modeling in R and Stan, the `glm()` and `brm()` functions in R provide a good introduction, because they conform to somewhat standard R conventions for model-fitting functions.  -->


<!-- ---- -->

<!-- # What does this mean? -->
<!-- * Minimal NONMEMese -->
<!-- * $\eta$ is not what you're used to -->
<!-- * No $\sigma$ (For the most part) -->
<!-- * No random effects (to start) -->

<!-- ---- -->

<!-- # Why start with binary data? -->

<!-- * The Bernoulli distribution for binary data is (in most respects) as simple a statistical distribution as there is. Good place to start for many basic statistical concepts.   -->
<!-- * There are fewer choices to make and fewer assumptions to check when dealing with binary data (e.g. as compared to time-to-event data).  -->

